// Generated by delombok at Sun Dec 02 13:03:44 UTC 2018
package org.fuchss.tools.tuple;

import java.io.Serializable;

/**
 * A simple tuple of three values
 *
 * @author Dominik Fuchss
 *
 * @param <A>
 *            the first type
 * @param <B>
 *            the second type
 * @param <C>
 *            the third type
 */
public final class Tuple3<A, B, C> implements Serializable {
	private static final long serialVersionUID = 3512228977823082170L;
	/**
	 * The first value.
	 */
	private final A first;
	/**
	 * The second value.
	 */
	private final B second;
	/**
	 * The third value.
	 */
	private final C third;

	/**
	 * Create a {@link Tuple3} by {@link Tuple2}
	 *
	 * @param <X>
	 *            the first type
	 * @param <Y>
	 *            the second type
	 * @param <Z>
	 *            the third type
	 *
	 * @param wxy
	 *            the first two values
	 * @param z
	 *            the third value
	 * @return the tuple
	 */
	static <X, Y, Z> Tuple3<X, Y, Z> of(Tuple2<X, Y> xy, Z z) {
		return Tuple3.of(xy.getFirst(), xy.getSecond(), z);
	}

	private Tuple3(final A first, final B second, final C third) {
		this.first = first;
		this.second = second;
		this.third = third;
	}

	public static <A, B, C> Tuple3<A, B, C> of(final A first, final B second, final C third) {
		return new Tuple3<>(first, second, third);
	}

	/**
	 * The first value.
	 *
	 * @return the first value
	 */
	public A getFirst() {
		return this.first;
	}

	/**
	 * The second value.
	 *
	 * @return the second value
	 */
	public B getSecond() {
		return this.second;
	}

	/**
	 * The third value.
	 *
	 * @return the third value
	 */
	public C getThird() {
		return this.third;
	}

	@Override
	public boolean equals(final Object o) {
		if (o == this) {
			return true;
		}
		if (!(o instanceof Tuple3)) {
			return false;
		}
		final Tuple3<?, ?, ?> other = (Tuple3<?, ?, ?>) o;
		final Object this$first = this.getFirst();
		final Object other$first = other.getFirst();
		if (this$first == null ? other$first != null : !this$first.equals(other$first)) {
			return false;
		}
		final Object this$second = this.getSecond();
		final Object other$second = other.getSecond();
		if (this$second == null ? other$second != null : !this$second.equals(other$second)) {
			return false;
		}
		final Object this$third = this.getThird();
		final Object other$third = other.getThird();
		if (this$third == null ? other$third != null : !this$third.equals(other$third)) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $first = this.getFirst();
		result = result * PRIME + ($first == null ? 43 : $first.hashCode());
		final Object $second = this.getSecond();
		result = result * PRIME + ($second == null ? 43 : $second.hashCode());
		final Object $third = this.getThird();
		result = result * PRIME + ($third == null ? 43 : $third.hashCode());
		return result;
	}

	@Override

	public String toString() {
		return "Tuple3(first=" + this.getFirst() + ", second=" + this.getSecond() + ", third=" + this.getThird() + ")";
	}
}
